
blank_issues_enabled: false
contact_links:
  - name: 🚨 Security Issue
    url: https://github.com/JosinaldoGJunior/financial-api-test-python/SECURITY.md
    about: Report vulnerabilities privately (follow our security policy)